on:
  push:
    tags:        
      - '*'
  workflow_dispatch:

name: Build

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: pagerduty-tui
            asset_name: pagerduty-tui-linux-amd64
          - os: windows-latest
            artifact_name: pagerduty-tui.exe
            asset_name: pagerduty-tui-windows-amd64
          - os: macos-latest
            artifact_name: pagerduty-tui
            asset_name: pagerduty-tui-macos-amd64

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --all-features
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
